package com.switchfully.order.domain.models.user;

public enum Feature {
    CAN_CREATE_ITEM, CAN_ORDER_ITEMS, CAN_RETRIEVE_ALL_CUSTOMERS, CAN_RETRIEVE_ALL_ITEMS, CAN_RETRIEVE_ORDERS,
    CAN_UPDATE_ITEMS, CAN_RETRIEVE_ORDER_THAT_ARE_SHIPPED_TOMORROW
}
